export const dataQuiz = [
    {
        id: 1,
        nama: "Tantangan Matematika",
        gambar: "/DaftarQuiz/MTK.jpg",
        deskripsi: "Uji kemampuan matematika Anda dengan soal-soal menantang.",
        kategori: "Matematika",
        jumlahSoal: 15,
        batasWaktu: 20,
    },
    {
        id: 2,
        nama: "Sejarah Indonesia",
        gambar: "/DaftarQuiz/Sejarah.jpg",
        deskripsi: "Seberapa banyak Anda tahu tentang sejarah Indonesia?",
        kategori: "Sejarah Indonesia",
        jumlahSoal: 12,
        batasWaktu: 18,
    },
    {
        id: 3,
        nama: "Pengetahuan Alam",
        gambar: "/DaftarQuiz/PengetahuanAlam.jpg",
        deskripsi: "Pelajari fakta menarik tentang dunia alam sekitar kita!",
        kategori: "Pengetahuan Alam",
        jumlahSoal: 10,
        batasWaktu: 15,
    },
    {
        id: 4,
        nama: "Astronomi",
        gambar: "/DaftarQuiz/Astronomi.jpg",
        deskripsi: "Jelajahi luar angkasa dan ketahui lebih dalam tentang alam semesta.",
        kategori: "Astronomi",
        jumlahSoal: 12,
        batasWaktu: 17,
    },
    {
        id: 5,
        nama: "Teknologi",
        gambar: "/DaftarQuiz/Teknologi.jpg",
        deskripsi: "Tes wawasan Anda tentang perkembangan teknologi modern.",
        kategori: "Teknologi",
        jumlahSoal: 15,
        batasWaktu: 20,
    },
    {
        id: 6,
        nama: "Pengetahuan Umum",
        gambar: "/DaftarQuiz/PengetahuanUmum.jpg",
        deskripsi: "Uji pengetahuan umum Anda dengan pertanyaan menarik!",
        kategori: "Pengetahuan Umum",
        jumlahSoal: 10,
        batasWaktu: 15,
    },
    {
        id: 7,
        nama: "Seni dan Budaya Indonesia",
        gambar: "/DaftarQuiz/SeniBudaya.jpg",
        deskripsi: "Kenali seni dan budaya Indonesia dari Sabang hingga Merauke.",
        kategori: "Seni dan Budaya Indonesia",
        jumlahSoal: 12,
        batasWaktu: 17,
    },
    {
        id: 8,
        nama: "Geografi",
        gambar: "/DaftarQuiz/Geografi.jpg",
        deskripsi: "Uji wawasan Anda tentang peta, benua, dan fenomena geografis dunia.",
        kategori: "Geografi",
        jumlahSoal: 12,
        batasWaktu: 17,
    },
    {
        id: 9,
        nama: "Sejarah Dunia",
        gambar: "/DaftarQuiz/SejarahDunia.jpg",
        deskripsi: "Jelajahi perjalanan sejarah dunia dari zaman kuno hingga modern.",
        kategori: "Sejarah",
        jumlahSoal: 20,
        batasWaktu: 25,
    },
    {
        id: 9,
        nama: "Sejarah Dunia",
        gambar: "/DaftarQuiz/SejarahDunia.jpg",
        deskripsi: "Jelajahi perjalanan sejarah dunia dari zaman kuno hingga modern.",
        kategori: "Sejarah",
        jumlahSoal: 20,
        batasWaktu: 25,
    },
];
